### ISSUE TITLE
Can I use ES6 in templates?

### ISSUE THREAD

**Issue by rtm7777** [zertosh/jstify#14]
Something like:
    ```<% pairs.forEach((pair) => { %>   
    <% }); %>```

**Comment by ruby-random** [comment]
@rtm7777 jstify itself is just a thin wrapper around <a href="https://lodash.com/docs#template">lodash</a> or <a href="http://underscorejs.org/#template">underscore.js</a>, so your question is a bit offtopic. However, you of course can use whatever you want within templates. If you run into delimiter escaping problem, you can give templating library different regex to find your interpolation blocks.
