### ISSUE TITLE
Cannot find module './templates/accounts/login.tpl'

### ISSUE THREAD

**Issue by matisoffn** [zertosh/jstify#24]
I'm implementing jstify like the README does, and I'm getting back a `Cannot find module 'templates/accounts/login.tpl'`

My code is almost identical to the README (`routes.js` file):

```javascript
var location = window.location.hash.slice(2)

var template = require('./templates/' + location + '.tpl')

var options = {}

$('#app').html(template(options))
```

File structure like so:

```
app
--templates
  --accounts
    --login.tpl
--routes.js
```

**Comment by blopker** [comment]
Are you using Browserify to package your JavaScript?

**Comment by matisoffn** [comment]
Yes I am

**Comment by matisoffn** [comment]
The template exists, and I'm requiring it as a variable just like the example in the README

**Comment by blopker** [comment]
There's a subtle difference. You're creating the path dynamically in the `require` statement, not hardcoding it. This is a Browserify limitation. Here's a related issue: https://github.com/substack/node-browserify/issues/377

**Comment by matisoffn** [comment]
Got it, thanks for your work.
